<?php

require_once(dirname(__FILE__).'/../../../../system/text/regularExpression/Regex.php');

/**
 * Test class for Regex.
 * Generated by PHPUnit on 2011-09-24 at 16:18:01.
 */
class RegexTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Regex
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Regex;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testEscape().
     */
    public function testEscape()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
